server:
    port: "8761"
eureka:
    instance:
        hostname: "${HOSTNAME}.eureka"
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: ${EUREKA_SERVER_ADDRESS}
