spring:
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: "true"
        defer-datasource-initialization: "true"
        show-sql: "true"
        hibernate:
            ddl-auto: create
    datasource:
        password: root
        username: root
        initialization-mode: always
        url: jdbc:mysql://localhost:3306/omf
        dbcp2:
            driver-class-name: com.mysql.cj.jdbc.Driver
    sql:
        init:
            mode: always
    application:
        name: search-service
logging:
    file:
        name: logs/dev.log
    logback:
        rollingpolicy:
            file-name-pattern: logs/dev-%d{yyyy-MM-dd}.%i.log
            max-history: "10"
            max-file-size: 20MB
server:
    port: "9090"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
  instance:
        preferIpAddress: true
        hostname: eureka-0