apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-app
  labels:
    app: order-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : order-service-app
  template:
    metadata:
      labels:
        app: order-service-app
    spec:
      containers:
      - name: order-service-app
        image: 30052001/order_service
        imagePullPolicy: Always
        ports:
          - containerPort: 4444

---

kind: Service
apiVersion: v1
metadata:
  name:  order-service-svc
spec:
  selector:
    app:  order-service-app
  ports:
  - port:  80
    targetPort:  4444
